using UnityEngine;

public class CableConnector : MonoBehaviour
{
    public GameObject cablePrefab;

    private Transform pointA = null;
    private Transform pointB = null;

    void Update()
    {
        if (Input.GetMouseButtonDown(0)) // Ù„Ù…Ø§ ØªØ¯ÙˆØ³ ÙƒÙ„ÙŠÙƒ Ø´Ù…Ø§Ù„
        {
            Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            RaycastHit hit;

            if (Physics.Raycast(ray, out hit))
            {
                if (pointA == null)
                {
                    pointA = hit.transform;
                    Debug.Log("ğŸŸ¢ I chose the first server: " + pointA.name);
                }
                else if (pointB == null)
                {
                    pointB = hit.transform;
                    Debug.Log("ğŸ”µ I chose the second server:" + pointB.name);
                    CreateCableBetweenPoints();
                }
            }
        }
    }

    void CreateCableBetweenPoints()
    {
        GameObject cable = Instantiate(cablePrefab);

        var cableScript = cable.GetComponent<OptimizedCable>();

        cableScript.startPoint = pointA;
        cableScript.endPoint = pointB;

        // Ù†Ø±Ø¬Ø¹ Ø§Ù„Ø§Ø®ØªÙŠØ§Ø± Ù„Ù„ÙˆØ¶Ø¹ Ø§Ù„Ø§ÙØªØ±Ø§Ø¶ÙŠ
        pointA = null;
        pointB = null;
    }
}
